# Generated by Django 4.2.7 on 2023-11-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='upload',
            field=models.FileField(null=True, upload_to='archivos_pdf'),
        ),
    ]
